/**
 * Default Dark — default production theme for symbiote-node UI
 *
 * Neutral Carbon-style shell with blue accents.
 *
 * @module symbiote-node/themes/default-dark
 */

const DEFAULT_DARK_TOKENS = {
  '--sn-theme-hue': '218',
  '--sn-theme-chroma': '89%',
  '--sn-theme-bg-lightness': '10%',
  '--sn-theme-surface-lightness': '13%',
  '--sn-theme-text-lightness': '94%',
  '--sn-theme-density': '1',
  '--sn-theme-radius-scale': '1',
  '--sn-theme-motion-scale': '1',
  '--sn-theme-elevation-scale': '1',

  '--sn-hue-base': '0',
  '--sn-hue-accent': 'var(--sn-theme-hue)',
  '--sn-hue-success': '122',
  '--sn-hue-warning': '36',
  '--sn-hue-danger': '4',
  '--sn-hue-data': '265',

  '--sn-sat': '0%',
  '--sn-sat-vivid': 'var(--sn-theme-chroma)',
  '--sn-sat-muted': '0%',

  '--sn-lit-bg': 'var(--sn-theme-bg-lightness)',
  '--sn-lit-surface': 'var(--sn-theme-surface-lightness)',
  '--sn-lit-border': '17%',
  '--sn-lit-hover': '27%',
  '--sn-lit-text': 'var(--sn-theme-text-lightness)',
  '--sn-lit-text-dim': '60%',
  '--sn-lit-accent': '63%',

  '--sn-alpha-overlay': '0.95',
  '--sn-alpha-subtle': '0.15',
  '--sn-alpha-faint': '0.06',

  '--sn-danger-color': '#f44336',
  '--sn-success-color': '#4caf50',
  '--sn-warning-color': '#ff9800',

  '--sn-bg': 'hsl(0 0% var(--sn-lit-bg))',
  '--sn-panel-bg': 'hsl(0 0% var(--sn-lit-surface))',
  '--sn-layout-bg': 'var(--sn-bg)',
  '--sn-layout-gap-bg': 'transparent',
  '--sn-layout-border': 'transparent',
  '--sn-layout-resizer-bg': 'transparent',
  '--sn-layout-resizer-hover-bg': 'rgba(255, 255, 255, 0.08)',
  '--sn-layout-resizer-size': '6px',
  '--sn-bg-overlay': 'rgba(0, 0, 0, 0.45)',
  '--sn-grid-dot': 'rgba(255, 255, 255, 0.06)',
  '--sn-grid-size': '20px',

  '--sn-node-bg': 'var(--sn-panel-bg)',
  '--sn-node-border': 'rgba(255, 255, 255, 0.1)',
  '--sn-node-radius': 'calc(6px * var(--sn-theme-radius-scale))',
  '--sn-node-shadow': '0 2px calc(8px * var(--sn-theme-elevation-scale)) rgba(0, 0, 0, 0.4)',
  '--sn-shadow-color': 'rgba(0, 0, 0, 0.4)',
  '--sn-node-header-bg': 'var(--sn-panel-bg)',
  '--sn-node-selected': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent))',
  '--sn-node-accent': 'var(--sn-node-selected)',
  '--sn-node-hover': '#444444',

  '--sn-font': "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  '--sn-font-mono': "'JetBrains Mono', 'Fira Code', monospace",
  '--sn-font-ui': "var(--sn-font)",
  '--sn-font-family': "var(--sn-font)",
  '--sn-icon-font': "'Material Symbols Outlined'",
  '--sn-text': '#f0f0f0',
  '--sn-text-dim': '#999999',

  '--sn-socket-size': '12px',
  '--sn-socket-border-width': '2px',

  '--sn-conn-color': 'var(--sn-node-selected)',
  '--sn-conn-width': '2',
  '--sn-conn-selected': '#f44336',

  '--sn-cat-server': 'var(--sn-node-selected)',
  '--sn-cat-instance': '#4caf50',
  '--sn-cat-control': '#ff9800',
  '--sn-cat-data': '#9c27b0',
  '--sn-cat-default': '#666666',
  '--sn-subgraph-accent': 'var(--sn-cat-data)',

  '--sn-ctx-bg': '#2a2a2a',
  '--sn-ctx-border': 'rgba(255, 255, 255, 0.1)',
  '--sn-ctx-color': '#f0f0f0',
  '--sn-ctx-hover': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.15)',

  '--sn-accent-bg': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.12)',
  '--sn-accent-bg-subtle': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.06)',
  '--sn-accent-border': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.2)',
  '--sn-accent-glow': '0 0 12px hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.12)',
  '--sn-success-border': 'rgba(76, 175, 80, 0.2)',
  '--sn-danger-border': 'rgba(244, 67, 54, 0.2)',
  '--sn-danger-bg': 'rgba(244, 67, 54, 0.12)',

  '--sn-comment-bg': 'rgba(255, 255, 255, 0.04)',
  '--sn-comment-border': 'rgba(255, 255, 255, 0.08)',
  '--sn-comment-radius': '4px',

  '--sn-toolbar-bg': 'rgba(34, 34, 34, 0.95)',
  '--sn-toolbar-border': 'rgba(255, 255, 255, 0.08)',
  '--sn-toolbar-color': '#999999',
  '--sn-toolbar-hover': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.18)',
  '--sn-toolbar-active': '#f0f0f0',
  '--sn-toolbar-danger': 'rgba(244, 67, 54, 0.22)',
  '--sn-toolbar-danger-color': '#f44336',

  '--sn-scrollbar-thumb': 'rgba(255, 255, 255, 0.08)',
  '--sn-scrollbar-thumb-hover': 'rgba(255, 255, 255, 0.25)',

  '--sn-tabs-height': '38px',
  '--sn-tabs-item-height': '32px',
  '--sn-tabs-bg': 'transparent',
  '--sn-tabs-border': 'rgba(255, 255, 255, 0.08)',
  '--sn-tabs-active-bg': 'var(--sn-node-bg)',
  '--sn-tabs-hover-bg': 'rgba(255, 255, 255, 0.04)',
  '--sn-tabs-divider': 'rgba(255, 255, 255, 0.1)',
  '--sn-tabs-radius': '8px 8px 0 0',

  '--sn-tree-gap': '4px',
  '--sn-tree-indent': '16px',
  '--sn-tree-row-height': 'calc(22px * var(--sn-theme-density))',
  '--sn-tree-row-min-height': 'calc(22px * var(--sn-theme-density))',
  '--sn-tree-row-padding-block': '2px',
  '--sn-tree-row-radius': 'calc(4px * var(--sn-theme-radius-scale))',
  '--sn-tree-row-hover-bg': 'var(--sn-node-hover)',
  '--sn-tree-row-selected-bg': 'var(--sn-accent-bg-subtle)',
  '--sn-tree-row-selected-border': 'transparent',
  '--sn-tree-row-focus-border': 'var(--sn-node-selected)',
  '--sn-tree-label-color': 'var(--sn-text-dim)',
  '--sn-tree-label-size': '12px',
  '--sn-tree-label-weight': '500',
  '--sn-tree-muted-color': 'var(--sn-text-dim)',
  '--sn-tree-icon-size': '15px',
  '--sn-tree-badge-radius': '8px',
  '--sn-tree-badge-bg': 'var(--sn-node-hover)',
  '--sn-tree-badge-color': 'var(--sn-text-dim)',
  '--sn-tree-badge-size': '10px',
  '--sn-tree-panel-font-size': '12px',
  '--sn-tree-panel-toolbar-gap': '6px',
  '--sn-tree-panel-toolbar-padding': '6px 8px',
  '--sn-tree-panel-row-min-height': 'var(--sn-tree-row-min-height)',
  '--sn-tree-panel-label-weight': 'var(--sn-tree-label-weight)',
  '--sn-card-bg': 'var(--sn-node-bg)',
  '--sn-card-border': 'var(--sn-node-border)',
  '--sn-card-radius': 'var(--sn-node-radius)',
  '--sn-card-padding': '14px',
  '--sn-card-margin-block-end': '12px',
  '--sn-card-hover-bg': 'var(--sn-node-hover)',
  '--sn-card-hover-border': 'var(--sn-node-selected)',
  '--sn-card-title-color': 'var(--sn-text-dim)',
  '--sn-card-title-size': '11px',
  '--sn-card-title-weight': '600',
  '--sn-card-title-margin-block-end': '12px',
  '--sn-card-footer-gap': '8px',
  '--sn-card-footer-margin-block-start': '16px',
  '--sn-card-footer-padding-block-start': '16px',
  '--sn-button-bg': 'var(--sn-node-bg)',
  '--sn-button-color': 'var(--sn-text)',
  '--sn-button-border': 'var(--sn-node-border)',
  '--sn-button-padding': '6px 14px',
  '--sn-button-radius': 'calc(8px * var(--sn-theme-radius-scale))',
  '--sn-button-gap': '6px',
  '--sn-button-min-height': '30px',
  '--sn-button-font-size': '12px',
  '--sn-button-font-weight': '500',
  '--sn-button-line-height': '1.2',
  '--sn-button-hover-bg': 'var(--sn-node-bg)',
  '--sn-button-hover-border': 'var(--sn-node-selected)',
  '--sn-button-disabled-opacity': '0.5',
  '--sn-button-primary-bg': 'var(--sn-node-selected)',
  '--sn-button-primary-border': 'var(--sn-node-selected)',
  '--sn-button-primary-color': 'var(--sn-text)',
  '--sn-button-primary-hover-filter': 'brightness(1.1)',
  '--sn-button-danger-bg': 'transparent',
  '--sn-button-danger-border': 'var(--sn-danger-color)',
  '--sn-button-danger-color': 'var(--sn-danger-color)',
  '--sn-button-danger-hover-bg': 'var(--sn-danger-color)',
  '--sn-button-danger-hover-border': 'var(--sn-danger-color)',
  '--sn-button-danger-hover-color': 'var(--sn-text)',
  '--sn-button-icon-size': '28px',
  '--sn-button-icon-font-size': '16px',
  '--sn-button-focus-ring': 'var(--sn-effect-focus-ring)',
  '--sn-field-margin-block-end': '12px',
  '--sn-field-label-margin-block-end': '4px',
  '--sn-field-label-color': 'var(--sn-text-dim)',
  '--sn-field-label-size': '11px',
  '--sn-field-label-weight': '500',
  '--sn-field-label-line-height': '1.2',
  '--sn-field-label-transform': 'uppercase',
  '--sn-field-control-bg': 'var(--sn-bg)',
  '--sn-field-control-border': 'var(--sn-node-border)',
  '--sn-field-control-color': 'var(--sn-text)',
  '--sn-field-control-padding': '8px 12px',
  '--sn-field-control-radius': 'calc(6px * var(--sn-theme-radius-scale))',
  '--sn-field-control-font-size': '12px',
  '--sn-field-control-line-height': '1.4',
  '--sn-field-control-focus-border': 'var(--sn-node-selected)',
  '--sn-field-control-focus-shadow': 'none',
  '--sn-field-placeholder-color': 'var(--sn-text-dim)',
  '--sn-field-textarea-min-height': '120px',
  '--sn-field-hint-margin-block-start': '4px',
  '--sn-field-hint-color': 'var(--sn-text-dim)',
  '--sn-field-hint-size': '11px',
  '--sn-field-hint-line-height': '1.4',
  '--sn-field-inline-gap': '8px',
  '--sn-field-compact-margin-block-end': '8px',
  '--sn-field-compact-control-padding': '6px 10px',
  '--sn-badge-bg': 'var(--sn-node-bg)',
  '--sn-badge-color': 'var(--sn-text-dim)',
  '--sn-badge-border': 'var(--sn-node-border)',
  '--sn-badge-padding': '2px 8px',
  '--sn-badge-radius': 'calc(12px * var(--sn-theme-radius-scale))',
  '--sn-badge-gap': '4px',
  '--sn-badge-font-size': '11px',
  '--sn-badge-font-weight': '500',
  '--sn-badge-line-height': '1.2',
  '--sn-badge-success-color': 'var(--sn-success-color)',
  '--sn-badge-success-border': 'var(--sn-success-color)',
  '--sn-badge-info-color': 'var(--sn-node-selected)',
  '--sn-badge-info-border': 'var(--sn-node-selected)',
  '--sn-badge-warning-color': 'var(--sn-warning-color)',
  '--sn-badge-warning-border': 'var(--sn-warning-color)',
  '--sn-badge-error-color': 'var(--sn-danger-color)',
  '--sn-badge-error-border': 'var(--sn-danger-color)',

  '--sn-list-item-bg': 'transparent',
  '--sn-list-item-hover-bg': 'var(--sn-node-hover)',
  '--sn-list-item-active-bg': 'var(--sn-accent-bg-subtle)',
  '--sn-list-item-active-border': 'var(--sn-node-selected)',
  '--sn-list-item-focus-border': 'var(--sn-node-selected)',
  '--sn-list-item-radius': 'calc(4px * var(--sn-theme-radius-scale))',
  '--sn-list-item-gap': '10px',
  '--sn-list-item-min-height': '34px',
  '--sn-list-item-padding': '8px 10px',
  '--sn-list-item-label-size': '12px',
  '--sn-list-item-description-size': '11px',
  '--sn-list-item-meta-size': '10px',

  '--sn-composer-bg': 'var(--sn-node-bg)',
  '--sn-composer-border': 'var(--sn-node-border)',
  '--sn-composer-action-bg': 'var(--sn-node-hover)',
  '--sn-composer-radius': 'calc(20px * var(--sn-theme-radius-scale))',
  '--sn-composer-control-gap': '8px',
  '--sn-composer-padding': '12px 20px 16px',
  '--sn-composer-body-padding': '8px 8px 8px 16px',
  '--sn-composer-input-min-height': '20px',

  '--sn-chat-bg': 'transparent',
  '--sn-chat-gap': '8px',
  '--sn-chat-message-bg': 'var(--sn-node-bg)',
  '--sn-chat-message-radius': '8px',
  '--sn-chat-transcript-padding': '24px 20px 12px',
  '--sn-chat-scroll-bottom': '92px',

  '--sn-source-bg': 'var(--sn-bg)',
  '--sn-source-header-bg': 'var(--sn-node-header-bg)',
  '--sn-source-border': 'var(--sn-node-border)',
  '--sn-source-toolbar-gap': '8px',
  '--sn-source-action-bg': 'var(--sn-bg)',
  '--sn-source-action-hover-bg': 'var(--sn-node-hover)',
  '--sn-source-action-radius': 'calc(4px * var(--sn-theme-radius-scale))',

  '--sn-source-editor-bg': 'var(--sn-bg)',
  '--sn-editor-bg': 'var(--sn-source-editor-bg)',
  '--sn-source-editor-color': 'var(--sn-text)',
  '--sn-editor-text': 'var(--sn-source-editor-color)',
  '--sn-editor-border': 'var(--sn-node-border)',
  '--sn-editor-radius': '0',
  '--sn-editor-font': 'var(--sn-font-mono)',
  '--sn-source-editor-padding': '14px 16px',
  '--sn-source-editor-font-size': '12px',
  '--sn-source-editor-line-height': '1.6',

  '--sn-loading-overlay-bg': 'var(--sn-bg)',
  '--sn-loading-bg': 'var(--sn-loading-overlay-bg)',
  '--sn-loading-text': 'var(--sn-text-dim)',
  '--sn-loading-accent': 'var(--sn-node-selected)',
  '--sn-loading-radius': '2px',
  '--sn-loading-overlay-gap': '16px',
  '--sn-loading-label-color': 'var(--sn-text-dim)',
  '--sn-loading-phase-color': 'var(--sn-node-selected)',
  '--sn-loading-track-bg': 'rgba(255, 255, 255, 0.08)',
  '--sn-loading-bar-bg': 'var(--sn-node-selected)',
  '--sn-loading-track-radius': '2px',

  '--sn-effect-hover-transition': 'background-color calc(120ms * var(--sn-theme-motion-scale)) ease, border-color calc(120ms * var(--sn-theme-motion-scale)) ease',
  '--sn-effect-focus-ring': '0 0 0 2px hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.35)',
  '--sn-effect-drag-shadow': '0 14px calc(32px * var(--sn-theme-elevation-scale)) rgba(0, 0, 0, 0.35)',
  '--sn-effect-loading-pulse': 'linear-gradient(90deg, transparent, hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.6), transparent)',

  '--sn-shape-fill': 'var(--sn-node-bg)',
  '--sn-shape-stroke': 'var(--sn-node-border)',
  '--sn-shape-stroke-width': '0.4',
  '--sn-frame-border-width': '2px',
  '--sn-frame-border-style': 'solid',
  '--sn-frame-radius': 'calc(12px * var(--sn-theme-radius-scale))',
  '--sn-frame-font': 'var(--sn-font)',
  '--sn-frame-font-size': '13px',

  '--bg-level-2': 'var(--sn-node-bg)',
  '--border-color': 'var(--sn-node-border)',
  '--text-color': 'var(--sn-text)',
  '--text-color-muted': 'var(--sn-text-dim)',
};

const DEFAULT_DARK_PALETTE_COLORS = {
  '--sn-theme-hue': '218',
  '--sn-theme-chroma': '89%',
  '--sn-theme-bg-lightness': '10%',
  '--sn-theme-surface-lightness': '13%',
  '--sn-theme-text-lightness': '94%',
  '--sn-theme-density': '1',
  '--sn-theme-radius-scale': '1',
  '--sn-theme-motion-scale': '1',
  '--sn-theme-elevation-scale': '1',
  '--sn-hue-base': '0',
  '--sn-hue-accent': 'var(--sn-theme-hue)',
  '--sn-hue-success': '122',
  '--sn-hue-warning': '36',
  '--sn-hue-danger': '4',
  '--sn-hue-data': '265',
  '--sn-sat': '0%',
  '--sn-sat-vivid': 'var(--sn-theme-chroma)',
  '--sn-sat-muted': '0%',
  '--sn-lit-bg': 'var(--sn-theme-bg-lightness)',
  '--sn-lit-surface': 'var(--sn-theme-surface-lightness)',
  '--sn-lit-border': '17%',
  '--sn-lit-hover': '27%',
  '--sn-lit-text': 'var(--sn-theme-text-lightness)',
  '--sn-lit-text-dim': '60%',
  '--sn-lit-accent': '63%',
  '--sn-alpha-overlay': '0.95',
  '--sn-alpha-subtle': '0.15',
  '--sn-alpha-faint': '0.06',
};

/** @type {import('./Theme.js').ThemeDefinition} */
export let DEFAULT_DARK = {
  name: 'default-dark',
  tokens: { ...DEFAULT_DARK_TOKENS },
};

/** @type {import('./Palette.js').PaletteDefinition} */
export let DEFAULT_DARK_PALETTE = {
  name: 'default-dark',
  colors: { ...DEFAULT_DARK_PALETTE_COLORS },
};
