/**
 * Default Dark — default production theme for symbiote-node UI
 *
 * Neutral Carbon-style shell with blue accents.
 *
 * @module symbiote-node/themes/default-dark
 */

const DEFAULT_DARK_TOKENS = {
  '--sn-hue-base': '0',
  '--sn-hue-accent': '218',
  '--sn-hue-success': '122',
  '--sn-hue-warning': '36',
  '--sn-hue-danger': '4',
  '--sn-hue-data': '265',

  '--sn-sat': '0%',
  '--sn-sat-vivid': '55%',
  '--sn-sat-muted': '0%',

  '--sn-lit-bg': '10%',
  '--sn-lit-surface': '13%',
  '--sn-lit-border': '17%',
  '--sn-lit-hover': '27%',
  '--sn-lit-text': '94%',
  '--sn-lit-text-dim': '60%',
  '--sn-lit-accent': '63%',

  '--sn-alpha-overlay': '0.95',
  '--sn-alpha-subtle': '0.15',
  '--sn-alpha-faint': '0.06',

  '--sn-danger-color': '#f44336',
  '--sn-success-color': '#4caf50',
  '--sn-warning-color': '#ff9800',

  '--sn-bg': '#1a1a1a',
  '--sn-panel-bg': '#222222',
  '--sn-layout-gap-bg': 'transparent',
  '--sn-layout-border': 'transparent',
  '--sn-layout-resizer-bg': 'transparent',
  '--sn-layout-resizer-hover-bg': 'rgba(255, 255, 255, 0.08)',
  '--sn-layout-resizer-size': '6px',
  '--sn-bg-overlay': 'rgba(0, 0, 0, 0.45)',
  '--sn-grid-dot': 'rgba(255, 255, 255, 0.06)',
  '--sn-grid-size': '20px',

  '--sn-node-bg': '#222222',
  '--sn-node-border': 'rgba(255, 255, 255, 0.1)',
  '--sn-node-radius': '6px',
  '--sn-node-shadow': '0 2px 8px rgba(0, 0, 0, 0.4)',
  '--sn-shadow-color': 'rgba(0, 0, 0, 0.4)',
  '--sn-node-header-bg': '#222222',
  '--sn-node-selected': '#4c8bf5',
  '--sn-node-hover': '#444444',

  '--sn-font': "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  '--sn-font-mono': "'JetBrains Mono', 'Fira Code', monospace",
  '--sn-font-ui': "var(--sn-font)",
  '--sn-font-family': "var(--sn-font)",
  '--sn-icon-font': "'Material Symbols Outlined'",
  '--sn-text': '#f0f0f0',
  '--sn-text-dim': '#999999',

  '--sn-socket-size': '12px',
  '--sn-socket-border-width': '2px',

  '--sn-conn-color': '#4c8bf5',
  '--sn-conn-width': '2',
  '--sn-conn-selected': '#f44336',

  '--sn-cat-server': '#4c8bf5',
  '--sn-cat-instance': '#4caf50',
  '--sn-cat-control': '#ff9800',
  '--sn-cat-data': '#9c27b0',
  '--sn-cat-default': '#666666',
  '--sn-subgraph-accent': 'var(--sn-cat-data)',

  '--sn-ctx-bg': '#2a2a2a',
  '--sn-ctx-border': 'rgba(255, 255, 255, 0.1)',
  '--sn-ctx-color': '#f0f0f0',
  '--sn-ctx-hover': 'rgba(76, 139, 245, 0.15)',

  '--sn-accent-bg': 'rgba(76, 139, 245, 0.12)',
  '--sn-accent-bg-subtle': 'rgba(76, 139, 245, 0.06)',
  '--sn-accent-border': 'rgba(76, 139, 245, 0.2)',
  '--sn-accent-glow': '0 0 12px rgba(76, 139, 245, 0.12)',
  '--sn-success-border': 'rgba(76, 175, 80, 0.2)',
  '--sn-danger-border': 'rgba(244, 67, 54, 0.2)',
  '--sn-danger-bg': 'rgba(244, 67, 54, 0.12)',

  '--sn-comment-bg': 'rgba(255, 255, 255, 0.04)',
  '--sn-comment-border': 'rgba(255, 255, 255, 0.08)',
  '--sn-comment-radius': '4px',

  '--sn-toolbar-bg': 'rgba(34, 34, 34, 0.95)',
  '--sn-toolbar-border': 'rgba(255, 255, 255, 0.08)',
  '--sn-toolbar-color': '#999999',
  '--sn-toolbar-hover': 'rgba(76, 139, 245, 0.18)',
  '--sn-toolbar-active': '#f0f0f0',
  '--sn-toolbar-danger': 'rgba(244, 67, 54, 0.22)',
  '--sn-toolbar-danger-color': '#f44336',

  '--sn-scrollbar-thumb': 'rgba(255, 255, 255, 0.08)',
  '--sn-scrollbar-thumb-hover': 'rgba(255, 255, 255, 0.25)',

  '--sn-tabs-height': '38px',
  '--sn-tabs-item-height': '32px',
  '--sn-tabs-bg': 'transparent',
  '--sn-tabs-border': 'rgba(255, 255, 255, 0.08)',
  '--sn-tabs-active-bg': 'var(--sn-node-bg)',
  '--sn-tabs-hover-bg': 'rgba(255, 255, 255, 0.04)',
  '--sn-tabs-divider': 'rgba(255, 255, 255, 0.1)',
  '--sn-tabs-radius': '8px 8px 0 0',

  '--sn-tree-gap': '4px',
  '--sn-tree-indent': '16px',
  '--sn-tree-row-height': '22px',
  '--sn-tree-row-min-height': '22px',
  '--sn-tree-row-padding-block': '2px',
  '--sn-tree-row-radius': '4px',
  '--sn-tree-row-hover-bg': 'var(--sn-node-hover)',
  '--sn-tree-row-selected-bg': 'var(--sn-accent-bg-subtle)',
  '--sn-tree-row-selected-border': 'transparent',
  '--sn-tree-row-focus-border': 'var(--sn-node-selected)',
  '--sn-tree-label-color': 'var(--sn-text-dim)',
  '--sn-tree-label-size': '12px',
  '--sn-tree-label-weight': '500',
  '--sn-tree-muted-color': 'var(--sn-text-dim)',
  '--sn-tree-icon-size': '15px',
  '--sn-tree-badge-radius': '8px',
  '--sn-tree-badge-bg': 'var(--sn-node-hover)',
  '--sn-tree-badge-color': 'var(--sn-text-dim)',
  '--sn-tree-badge-size': '10px',

  '--sn-list-item-bg': 'transparent',
  '--sn-list-item-hover-bg': 'var(--sn-node-hover)',
  '--sn-list-item-active-bg': 'var(--sn-accent-bg-subtle)',
  '--sn-list-item-active-border': 'var(--sn-node-selected)',
  '--sn-list-item-focus-border': 'var(--sn-node-selected)',
  '--sn-list-item-radius': '4px',
  '--sn-list-item-gap': '10px',
  '--sn-list-item-min-height': '34px',
  '--sn-list-item-padding': '8px 10px',
  '--sn-list-item-label-size': '12px',
  '--sn-list-item-description-size': '11px',
  '--sn-list-item-meta-size': '10px',

  '--sn-composer-bg': 'var(--sn-node-bg)',
  '--sn-composer-action-bg': 'var(--sn-node-hover)',
  '--sn-composer-radius': '20px',
  '--sn-composer-control-gap': '8px',
  '--sn-composer-padding': '12px 20px 16px',
  '--sn-composer-body-padding': '8px 8px 8px 16px',
  '--sn-composer-input-min-height': '20px',

  '--sn-chat-bg': 'transparent',
  '--sn-chat-gap': '8px',
  '--sn-chat-message-bg': 'var(--sn-node-bg)',
  '--sn-chat-message-radius': '8px',
  '--sn-chat-transcript-padding': '24px 20px 12px',
  '--sn-chat-scroll-bottom': '92px',

  '--sn-source-bg': 'var(--sn-bg)',
  '--sn-source-header-bg': 'var(--sn-node-header-bg)',
  '--sn-source-border': 'var(--sn-node-border)',
  '--sn-source-toolbar-gap': '8px',
  '--sn-source-action-bg': 'var(--sn-bg)',
  '--sn-source-action-hover-bg': 'var(--sn-node-hover)',
  '--sn-source-action-radius': '4px',

  '--sn-source-editor-bg': 'var(--sn-bg)',
  '--sn-editor-bg': 'var(--sn-source-editor-bg)',
  '--sn-source-editor-color': 'var(--sn-text)',
  '--sn-editor-text': 'var(--sn-source-editor-color)',
  '--sn-editor-border': 'var(--sn-node-border)',
  '--sn-editor-radius': '0',
  '--sn-editor-font': 'var(--sn-font-mono)',
  '--sn-source-editor-padding': '14px 16px',
  '--sn-source-editor-font-size': '12px',
  '--sn-source-editor-line-height': '1.6',

  '--sn-loading-overlay-bg': 'var(--sn-bg)',
  '--sn-loading-bg': 'var(--sn-loading-overlay-bg)',
  '--sn-loading-text': 'var(--sn-text-dim)',
  '--sn-loading-accent': 'var(--sn-node-selected)',
  '--sn-loading-radius': '2px',
  '--sn-loading-overlay-gap': '16px',
  '--sn-loading-label-color': 'var(--sn-text-dim)',
  '--sn-loading-phase-color': 'var(--sn-node-selected)',
  '--sn-loading-track-bg': 'rgba(255, 255, 255, 0.08)',
  '--sn-loading-bar-bg': 'var(--sn-node-selected)',
  '--sn-loading-track-radius': '2px',

  '--sn-effect-hover-transition': 'background-color 120ms ease, border-color 120ms ease',
  '--sn-effect-focus-ring': '0 0 0 2px rgba(76, 139, 245, 0.35)',
  '--sn-effect-drag-shadow': '0 14px 32px rgba(0, 0, 0, 0.35)',
  '--sn-effect-loading-pulse': 'linear-gradient(90deg, transparent, rgba(76, 139, 245, 0.6), transparent)',

  '--sn-shape-fill': 'var(--sn-node-bg)',
  '--sn-shape-stroke': 'var(--sn-node-border)',
  '--sn-shape-stroke-width': '0.4',

  '--bg-level-2': 'var(--sn-node-bg)',
  '--border-color': 'var(--sn-node-border)',
  '--text-color': 'var(--sn-text)',
  '--text-color-muted': 'var(--sn-text-dim)',
};

const DEFAULT_DARK_PALETTE_COLORS = {
  '--sn-hue-base': '0',
  '--sn-hue-accent': '218',
  '--sn-hue-success': '122',
  '--sn-hue-warning': '36',
  '--sn-hue-danger': '4',
  '--sn-hue-data': '265',
  '--sn-sat': '0%',
  '--sn-sat-vivid': '55%',
  '--sn-sat-muted': '0%',
  '--sn-lit-bg': '10%',
  '--sn-lit-surface': '13%',
  '--sn-lit-border': '17%',
  '--sn-lit-hover': '27%',
  '--sn-lit-text': '94%',
  '--sn-lit-text-dim': '60%',
  '--sn-lit-accent': '63%',
  '--sn-alpha-overlay': '0.95',
  '--sn-alpha-subtle': '0.15',
  '--sn-alpha-faint': '0.06',
};

/** @type {import('./Theme.js').ThemeDefinition} */
export let DEFAULT_DARK = {
  name: 'default-dark',
  tokens: { ...DEFAULT_DARK_TOKENS },
};

/** @type {import('./Palette.js').PaletteDefinition} */
export let DEFAULT_DARK_PALETTE = {
  name: 'default-dark',
  colors: { ...DEFAULT_DARK_PALETTE_COLORS },
};
